---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(datasus)
library(sidrar)
```



# 1. Mortes por acidente de trânsito

```{r mortes}
codigos <- c(
  paste0("V", formatC(1:6, width = 2, flag = "0")),
  paste0("V", formatC(9:89, width = 2, flag = "0")))

obitos <- sim_obt10_mun(
  coluna = "Ano do Óbito",
  conteudo = 2,    #Óbitos por ocorrência
  capital = c(110020, 120040, 130260, 140010, 150140, 160030, 172100, 211130, 221100, 230440, 240810, 250750, 261160, 270430, 280030, 292740, 310620, 320530, 330455, 355030, 410690, 420540, 431490, 500270, 510340, 520870, 530010),    #código IBGE de todas as capitais
  periodo = c("2011", "2017"),
  # grupo_cid10 = c("Pedestre traumatizado em um acidente de transporte", "Ciclista traumatizado em um acidente de transporte", "Motociclista traumat em um acidente de transporte", "Ocupante triciclo motorizado traumat acid transp", "Ocupante automóvel traumat acidente transporte", "Ocupante caminhonete traumat acidente transporte", "Ocupante veíc transp pesado traumat acid transp", "Ocupante ônibus traumat acidente de transporte", "Outros acidentes de transporte terrestre")
  categoria_cid10 = codigos
)
```



# 2. População

```{r populacao}
populacao <- get_sidra(
  6579,
  period = c("2011", "2017"),
  geo = "City",
  geo.filter = list("City" = c(1100205, 1200401, 1302603, 1400100, 1501402, 1600303, 1721000, 2111300, 2211001, 2304400, 2408102, 2507507, 2611606, 2704302, 2800308, 2927408, 3106200, 3205309, 3304557, 3550308, 4106902, 4205407, 4314902, 5002704, 5103403, 5208707, 5300108))
)
```

# 3. Data frame

```{r df}
# tidying obitos

obitos_tidy <- obitos %>%
  pivot_longer(
    cols = c(`2011`, `2017`),
    names_to = "ano",
    values_to = "obitos"
    ) %>%
  filter(`Município` != "TOTAL") %>%
  mutate(
    municip_cod = str_sub(`Município`, end = 6)
  )



# tidying populacao

populacao_tidy <- populacao %>%
  mutate(
    municip_cod = str_sub(`Município (Código)`, end = 6)
  )



# merge

df <- full_join(obitos_tidy, populacao_tidy, by = c("municip_cod", "ano" = "Ano"))
```




# 4. Cálculo taxa

```{r taxa}
df2 <- df %>%
  mutate(
    taxa = obitos / Valor * 10^5
    ) %>%
    select(municipio = `Município.x`, ano, taxa)
```

Os valores das taxas não estão batendo com os dados apresentados pelo jornal.
Talvez há uma diferença no conceito de "mortes no trânsito".
Quais códigos CID foram utilizados?



df com a diferença de taxas entre 2017 e 2011.
O código ficou um tanto quanto gambiarra mas funcionou.

```{r}
df3 <- df2 %>% split(.$municipio) %>%
  map_df(function (x) x$taxa[2]-x$taxa[1]) %>%
  pivot_longer(everything(), names_to = "capital", values_to = "diff")
```
